name: Deploy

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted

    steps:
      - run: echo "owata \(^o^)/"

      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Deploy app
        env:
          KEY: ${{ secrets.ENCRYPTION_KEY }}
        run: |
          cp -r client/ src/ deno.json deno.lock index.ts /var/www/owata/
          cd /var/www/owata
          pm2 delete owata
          deno cache index.ts # preload dependencies
          pm2 start --interpreter="deno" --interpreter-args="run --allow-read --allow-net --allow-env" index.ts --name owata
